function [ fV, dV, d2V, fd2cov, fdcov, dd2cov ] ...
                  = cfield_params_est( cfield, dcfield, dcfield2, do_stat )
% CFIELD_PARAMS_EST( lat_data, params ) estimates the different parameters 
% of a convolution field generated by smoothing lat_data with the
% parameters specificed in params.
%--------------------------------------------------------------------------
% ARGUMENTS
% Mandatory
%   field   an object of field class giving the field 
%   dcfield    an object of field class giving the derivative of the
%              original field 
%   dcfield2   an object of field class giving the second derivative of the 
%              original field  
%   do_stat    0/1: whether or not to average across everything to obtain 
%              an estimate under the assumption of stationarity. Default
%              is 0, i.e. assuming non-stationary fields
% Optional
%--------------------------------------------------------------------------
% OUTPUT
% 
%--------------------------------------------------------------------------
% EXAMPLES
% 
%--------------------------------------------------------------------------
% AUTHOR: Samuel Davenport
%--------------------------------------------------------------------------

%%  Check mandatory input and get important constants
%--------------------------------------------------------------------------

%%  Add/check optional values
%--------------------------------------------------------------------------
if ~exist( 'do_stat', 'var' )
   % Default value
   do_stat = 0;
end

%%  Main Function Loop
%--------------------------------------------------------------------------
% cfield = convfield(lat_data, params);
% dcfield = convfield(lat_data, params, 1);
% dcfield2 = convfield(lat_data, params, 2);

D = cfield.D;
nsubj = cfield.fibersize;
if D == 1
        fV = var( cfield.field,  0, D+1 );
        dV  = var( dcfield.field, 0, D+1 );
        d2V  = var( dcfield2.field, 0, D+1 );
        fdcov = sum( ( dcfield.field - mean( dcfield.field, D+1 ) )...
                                .* cfield.field, D+1 ) / ( nsubj - 1 );
        fd2cov = sum( ( dcfield2.field - mean( dcfield.field, D+1 ) )...
                                .* cfield.field, D+1 ) / ( nsubj - 1 );
        dd2cov = sum( ( dcfield.field - mean( dcfield.field, D+1 ) )...
                                .* dcfield2.field, D+1 ) / ( nsubj - 1 );
else
    error('D > 1 has not yet been implemented')
end

% Under stationarity, take the average of the parameters
if do_stat == 1
    fV = mean(fV(:));
    dV = mean(dV(:));
    d2V = mean(d2V(:));
    fdcov = mean(fdcov(:));
    fd2cov = mean(fd2cov(:));
    dd2cov = mean(dd2cov(:));
end


end

